- platformplugin/xcbnativeeventfilter.cpp
see: https://github.com/linuxdeepin/qt5integration/pull/15
fix: https://github.com/linuxdeepin/internal-discussion/issues/1373
修复在没有任何屏幕的情况下插入一个屏幕后，Qt字体变小（开启了高分屏缩放时）
> fix: call QDeepinTheme::updateScaleLogcailDpi when screen added

- platformplugin/xcbnativeeventfilter.cpp
Change-Id: Ied6745da56fa3a873d66a2d8e5385cd17c2fb273
> fix: compatibility with Qt 5.12+

- platformplugin/dframewindow.cpp
- platformplugin/dplatformbackingstore.cpp
- platformplugin/dplatformbackingstorehelper.cpp
- platformplugin/dplatformnativeinterfacehook.cpp
- platformplugin/dplatformopenglcontexthelper.cpp
- platformplugin/dplatformwindowhelper.cpp
- platformplugin/dxcbwmsupport.cpp
- platformplugin/dxcbwmsupport.h
- platformplugin/global.h
- platformplugin/utility.h
- platformplugin/utility_x11.cpp
修复当默认窗口位深设置为16位时，dde-dock窗口内容为全黑的问题
> 支持窗口位深小于24的图形环境

- platformplugin/dplatformintegration.cpp
- platformplugin/dplatformintegration.h
- platformplugin/dxcbxsettings.cpp
- platformplugin/dxcbxsettings.h
- platformplugin/linux.pri
- platformplugin/xcbnativeeventfilter.cpp
document:
https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/
Supports:
* Net/DoubleClickTime
* Net/CursorBlinkTime
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linuxdeepin/qt5dxcb-plugin/23)
> feat: support for standard xsettings properties

- platformplugin/dnativesettings.cpp
- platformplugin/dnativesettings.h
- platformplugin/dnotitlebarwindowhelper.cpp
- platformplugin/dnotitlebarwindowhelper.h
- platformplugin/dplatformintegration.cpp
- platformplugin/dplatformintegration.h
- platformplugin/dplatformnativeinterfacehook.cpp
- platformplugin/dplatformnativeinterfacehook.h
- platformplugin/dxcbxsettings.cpp
- platformplugin/dxcbxsettings.h
- platformplugin/global.h
- platformplugin/qt5platform-plugin.pro
- platformplugin/utility.h
- platformplugin/utility_x11.cpp
- platformplugin/vtablehook.cpp
- platformplugin/vtablehook.h
- platformplugin/xcbnativeeventfilter.cpp
对于开启了无titlebar模式的窗口，支持设置窗口阴影等参数
> feat: support set window properties for no titlebar window

- platformplugin/dnotitlebarwindowhelper.cpp
> fix: window radius value multiplied by window scaling

- platformplugin/dnotitlebarwindowhelper.cpp
- platformplugin/dnotitlebarwindowhelper.h
fix window blur area is wrong if the window size is changed
当窗口是顶层窗口时，不需要使用窗口的大小和位置裁剪模糊区域
> fix: D'not clip window blur area

- platformplugin/dnativesettings.cpp
- platformplugin/dxcbxsettings.cpp
- platformplugin/dxcbxsettings.h
> feat: support custom use window property for xsettings

- platformplugin/dxcbxsettings.cpp
> fix: Immediate ungrab server

- platformplugin/windoweventhook.cpp
I'm not sure whether this is correct though...
> fix: build failure under Qt 5.13.0

- platformplugin/dnativesettings.cpp
- platformplugin/dnativesettings.h
- platformplugin/dplatformintegration.cpp
- platformplugin/dxcbxsettings.cpp
- platformplugin/dxcbxsettings.h
> feat: support signal for DNativeSettings

- xcb/windoweventhook.cpp
According to the context, it should be window instead.
Issue: Fix part of #47
> fix: build failure due to undefined "xcbWindow"

- xcb/windoweventhook.cpp
Ref: https://codereview.qt-project.org/c/qt/qtbase/+/267242
> fix: timer interval according to upstream Qt

- xcb/utility_x11.cpp
correct typos in xcb/utility_x11.cpp
Log:
> chore: correct typos in xcb/utility_x11.cpp

- src/global.cpp
- src/global.h
- src/src.pri
- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- wayland/dwayland/dwaylandinterfacehook.cpp
- wayland/dwayland/dwaylandinterfacehook.h
- wayland/wayland-shell/dwaylandshellmanager.cpp
支持wayland上的分屏需求
Log:
Task: https://pms.uniontech.com/task-view-101737.html
Influence: wayland平台的分屏功能
> feat: 支持wayland上的分屏需求

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
- wayland/wayland-shell/wayland-shell.pro
全局键盘key值经过qtwayland处理之后qt才能识别
参考qtwayland处理方式添加xkbcommon处理。
Log:
Influence: wayland全局按键
> chore: 全局按键的键值处理

- wayland/wayland-shell/dwaylandshellmanager.cpp
This reverts commit  75a7eb5f
恢复wayland分屏功能代码
Log: 恢复wayland分屏功能的支持
Influence: wayland分屏功能
> chore: 恢复wayland分屏功能的支持

- src/vtablehook.h
更新vtablehook以支持lambda表达式
Log:
Influence:
> chore: 更新vtablehook以支持lambda表达式

- wayland/dwayland/dwayland.pro
- wayland/wayland-shell/wayland-shell.pro
将wayland中用不到的源文件排除在外
Log:
Influence:
> chore: 精简wayland插件依赖的源文件

- src/vtablehook.h
- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
- wayland/wayland-shell/main.cpp
重构waylandi-shell部分代码
Log:
Influence:
> chore: 重构wayland-shell

- wayland/wayland-shell/dkeyboard.cpp
- wayland/wayland-shell/dkeyboard.h
- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
- wayland/wayland-shell/wayland-shell.pro
修改了一些code style
整理了sendProperty 里面的一些内容
Log:
Influence:
> 重构wayland shell manager

- wayland/wayland-shell/dwaylandshellmanager.cpp
改变了设置窗口位置的部分逻辑
增加了keepabove的原始调用逻辑
Log:
Influence: 窗口置顶、窗口位置设置
> refactor: 修改style与部分代码逻辑

- wayland/dwayland/dhighdpi.cpp
- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- wayland/dwayland/dnotitlebarwindowhelper_wl.h
- wayland/dwayland/dwayland.pro
- wayland/dwayland/dwaylandintegration.cpp
- wayland/dwayland/dwaylandintegration.h
- wayland/dwayland/dwaylandinterfacehook.cpp
- wayland/dwayland/dwaylandinterfacehook.h
- wayland/dwayland/dxsettings.cpp
- wayland/dwayland/dxsettings.h
- wayland/dwayland/main.cpp
- wayland/wayland-shell/dwaylandshellmanager.cpp
改变一些codestyle，分支判断的逻辑结构
Log:
Influence:
> refactor: 主要更新dwayland部分的代码

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
触摸屏下的窗口移动的调用未添加冗余距离
容易导致双击事件被识别为窗口移动
Log:
Bug: https://pms.uniontech.com/bug-view-113329.html
Influence: 窗口的移动和最大最小化
> fix: wayland 环境触摸不灵敏

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
> chore: 支持通过QWindowFlags设置窗口置顶

- wayland/wayland-shell/config.tests/wayland_test/main.cpp
- wayland/wayland-shell/config.tests/wayland_test/wayland_test.pro
- wayland/wayland-shell/main.cpp
- wayland/wayland-shell/wayland-shell.pro
Add a condition check for wayland module, which must satisfy qtwayland and some modified header files.
Log:
> feat: add wayland functional test

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- wayland/wayland-shell/main.cpp
> refactor: v23 shell兼容性支持以及创建流程优化

- wayland/wayland-shell/config.tests/wayland_test/main.cpp
- wayland/wayland-shell/wayland-shell.pro
之前加了兼容性测试程序，程序未兼容低版本，报错信息不明显
Log:
> chore: Qt5.11 版本兼容性测试提示信息

- wayland/wayland-shell/config.tests/wayland_test/main.cpp
- wayland/wayland-shell/config.tests/wayland_test/wayland_test.pro
- wayland/wayland-shell/wayland-shell.pro
兼容性测试程序不能编过
Log: 
Bug: https://pms.uniontech.com/bug-view-138465.html
> fix: 社区版兼容性测试失败导致应用无法启动

- debian/source/format
- wayland/wayland-shell/config.tests/wayland_test/main.cpp
- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/wayland-shell.pro
missing QPainterPath header
Log:
> fix: missing QPainterPath header

- xcb/libqt5xcbqpa-dev/5.15.5/qxcbatom.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbbackingstore.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbclipboard.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbconnection.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbconnection_basic.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbcursor.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbdrag.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbeventdispatcher.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbeventqueue.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbexport.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbimage.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbintegration.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbkeyboard.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbmime.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbnativeinterface.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbobject.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbscreen.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbsessionmanager.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbsystemtraytracker.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbvulkaninstance.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbvulkanwindow.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbwindow.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbwmsupport.h
- xcb/libqt5xcbqpa-dev/5.15.5/qxcbxsettings.h
Log: Add support for Qt 5.15.5
> feat(libqt5xcbqpa-dev): support Qt 5.15.5

- wayland/dwayland/dwaylandintegration.cpp
判断逻辑错误，结合model和name一起判断
Log: 修复主屏变化后，qt未发出响应信号的问题
Influence: wayland下很可能出现切换主屏，任务栏不跟随切换的问题
Bug: https://pms.uniontech.com/bug-view-150573.html
Change-Id: Icaa4a6910421daf7361388e1c761dabc654129dd
> fix: 修复主屏变化后，qt未发出响应信号的问题

- LICENSE
change LICENSE from GPL-v3 to LGPL-v3+
Log: none
> docs: GPL-v3 to LGPL-v3+

- wayland/dwayland/dwaylandintegration.cpp
fix build error
Log: none
Change-Id: I9a30a6d2714ed17ddf1bcacaca86cbe90f05ca18
> fix(build): build error

- .reuse/dep5
使用通配符代替原来的具体文件,方便扩展
Log:
Change-Id: I6c57bebf78db2b215b26026e93f5a24d17c6047e
> doc: update .reuse/dep

- xcb/libqt5xcbqpa-dev/5.15.6/qxcbatom.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbbackingstore.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbclipboard.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbconnection.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbconnection_basic.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbcursor.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbdrag.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbeventdispatcher.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbeventqueue.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbexport.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbimage.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbintegration.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbkeyboard.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbmime.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbnativeinterface.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbobject.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbscreen.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbsessionmanager.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbsystemtraytracker.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbvulkaninstance.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbvulkanwindow.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbwindow.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbwmsupport.h
- xcb/libqt5xcbqpa-dev/5.15.6/qxcbxsettings.h
Add support for 5.15.6
Log:  Add support for 5.15.6
Influence: 打包 构建
> feat: Add support for 5.15.6

- .reuse/dep5
- debian/control
- wayland/wayland-shell/config.tests/deepin-kwin-test/deepin-kwin-test.pro
- wayland/wayland-shell/config.tests/deepin-kwin-test/main.cpp
- wayland/wayland-shell/config.tests/wayland_test/main.cpp
- wayland/wayland-shell/config.tests/wayland_test/wayland_test.pro
- wayland/wayland-shell/dkeyboard.h
- wayland/wayland-shell/dwaylandshellmanager.h
- wayland/wayland-shell/main.cpp
- wayland/wayland-shell/wayland-shell.pro
- wayland/wayland-shell/wayland_depends.pri
use dwayland instead of kwayland
Log: kwayland -> dwayland
Influence: dwayalnd
Change-Id: I8e2b85af335e4434114f745ca4d7a795753c9070
> feat: kwayland to dwayland

- wayland/dwayland/dwaylandintegration.cpp
添加一部分日志用于日后分析
Log: 无
Influence: 无
Change-Id: I9952d6b7e335cb13e5d374199c48d891facbb94c
> test: 添加一部分日志用于日后分析

- xcb/libqt5xcbqpa-dev/5.15.7/qxcbatom.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbbackingstore.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbclipboard.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbconnection.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbconnection_basic.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbcursor.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbdrag.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbeventdispatcher.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbeventqueue.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbexport.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbimage.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbintegration.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbkeyboard.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbmime.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbnativeinterface.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbobject.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbscreen.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbsessionmanager.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbsystemtraytracker.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbvulkaninstance.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbvulkanwindow.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbwindow.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbwmsupport.h
- xcb/libqt5xcbqpa-dev/5.15.7/qxcbxsettings.h
Add support for 5.15.7
Log:  Add support for 5.15.7
Influence: 打包 构建
> feat: Add support for 5.15.7

- debian/changelog
- debian/source/format
update changelog
Log: update changelog
Change-Id: I2b554d0a0dfccee929d81fdaa327cd77b1011649
> chore: update changelog

- wayland/dwayland/dwaylandintegration.cpp
修改小概率屏幕信息错误的问题
Log: 修改小概率屏幕信息错误的问题
Influence: 任务栏主屏显示错位
Bug: https://pms.uniontech.com/bug-view-161077.html
Change-Id: I2aff5ae6fd9d7fa072aa9e1a93064f38a052e016
> fix: 修改小概率屏幕信息错误的问题

- .reuse/dep5
- linglong.yaml
add linglong.yaml to support linglong build
see https://linglong.dev/guide/ll-builder/manifests.html
Log: linglong
Influence: linglong
Change-Id: Ia5ab023f7c3b9d8c1a78055645e868920e57e367
> feat: add linglong build support

- src/vtablehook.cpp
- src/vtablehook.h
> fix: sync with dtkcore

- linglong.yaml
According to #164 this project should not depend on any dtk*
> fix: remove redundant dtk dependencies

- .obs/workflows.yml
- archlinux/PKGBUILD
> chore: modify PKGBUILD support OBS

- .obs/workflows.yml
> fix: typo ddeepin -> deepin

- CMakeLists.txt
- archlinux/PKGBUILD
- debian/rules
- src/dapplicationeventmonitor.cpp
- src/dnativesettings.cpp
- src/dselectedtexttooltip.cpp
- src/dxcbxsettings.cpp
- wayland/dwayland/CMakeLists.txt
- wayland/wayland-shell/CMakeLists.txt
- wayland/wayland-shell/config.tests/deepin-kwin-test/CMakeLists.txt
- wayland/wayland-shell/config.tests/wayland_test/CMakeLists.txt
- wayland/wayland-shell/main.cpp
- xcb/CMakeLists.txt
- xcb/dforeignplatformwindow_x11.cpp
- xcb/dnotitlebarwindowhelper.cpp
- xcb/dplatformbackingstorehelper.cpp
- xcb/dplatformintegration.cpp
- xcb/dplatformintegration.h
- xcb/dplatformopenglcontexthelper.cpp
- xcb/dplatformwindowhelper.cpp
- xcb/linux.cmake
- xcb/utility.h
- xcb/utility_x11.cpp
- xcb/windoweventhook.cpp
- xcb/xcbnativeeventfilter.cpp
- xcb/xcbnativeeventfilter.h
xcb module compatible with Qt6.
wayland module temporarily don't compatible with Qt6, as a result of dwayland or kwayland doesn't support Qt6.
Log: Support Qt6
> chore: Support Qt6

- xcb/CMakeLists.txt
add the XcbQpaPrivate module in qt6 version.
Log: add the XcbQpaPrivate module int qt6 version
> chore: add the XcbQpaPrivate module in qt6 version

- xcb/dforeignplatformwindow_x11.cpp
- xcb/dplatformbackingstorehelper.cpp
- xcb/dplatformintegration.cpp
- xcb/dplatformopenglcontexthelper.cpp
- xcb/utility.h
- xcb/utility_x11.cpp
resolve the warnings about deprecated-declarations
Log: resolve the warnings about deprecated-declarations
> chore: resolve the warnings about deprecated-declarations

- wayland/wayland-shell/config.tests/deepin-kwin-test/CMakeLists.txt
- wayland/wayland-shell/config.tests/wayland_test/CMakeLists.txt
resolve the warning about didn't set minimum version of cmake
Log: resolve the warning from cmake
> chore: resolve the warning from cmake

- wayland/dwayland/CMakeLists.txt
- xcb/CMakeLists.txt
add source files about symbol
Log: fix the issue that undefine symbol
> fix: undefine symbol

- src/dxcbxsettings.cpp
use invalid address after the memory is reallocated
Log: fix the issue that heap use after free
> fix: heap use after free

- xcb/dnotitlebarwindowhelper.cpp
QVariant couldn't be converted to QStringList,
because QVariant's value is QString type.
Log: fix the issue that unit test failed
> fix: unit test failed (setWindowRadius)

- xcb/dnotitlebarwindowhelper.cpp
This reverts commit 236869e1a4fd191c0b2207b3d965ea6b9817aefe.
> Revert "fix: unit test failed (setWindowRadius)"

- tests/CMakeLists.txt
- tests/src/ut_dapplicationeventmonitor.cpp
- tests/src/ut_dbackingstoreproxy.cpp
- tests/src/ut_ddesktopinputselectioncontrol.cpp
- tests/src/ut_dframewindow.cpp
- tests/src/ut_dinputselectionhandle.cpp
- tests/src/ut_dnativesettings.cpp
- tests/src/ut_dnotitlebarwindowhelper.cpp
- tests/src/ut_dopenglpaintdevice.cpp
- tests/src/ut_dxcbxsettings.cpp
- tests/src/ut_global.cpp
- tests/src/ut_utility.cpp
- tests/test-recoverage.sh
add unit test ut_dxcbxsettings
Log: add unit test ut_dxcbsettings
> chore: add unit test ut_dxcbxsettings

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/main.cpp
- tests/src/ut_dbackingstoreproxy.cpp
- tests/src/ut_dnotitlebarwindowhelper.cpp
- xcb/CMakeLists.txt
link to target directly, instead of compiling the source code.
Log: Link to target directly on unit test
> chore: link to target directly on unit test

- xcb/CMakeLists.txt
remove XcbQpaPrivate module on qt6
Log: remove XcbQpaPrivate module on qt6
> chore: remove XcbQpaPrivate module on qt6

- debian/control
add dtkcommon depency
Log: add dtkcommon depency
> chore: add dtkcommon depency

- tests/src/ut_dopenglpaintdevice.cpp
- xcb/CMakeLists.txt
> fix: Compiling error for test in qt6.4.2

- xcb/CMakeLists.txt
> chore: find DtkBuildHelper only on EnableCov

- wayland/dwayland/CMakeLists.txt
Make sure compiler can find out headers of wayland and xkbcommon
Log:
> fix: link wayland and x11 libraries

- .github/workflows/call-synchronize-to-dtk6.yml
- .reuse/dep5
- .syncexclude
> feat: add workflow for sync to dtk6

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
> chore: revert 706c4c95 on dwayland

- src/dnativesettings.cpp
switch quantity not an integer
> fix(build): qt6 build failed

- debian/changelog
> chore: bump version to 5.6.20

- src/dnativesettings.cpp
- xcb/dnotitlebarwindowhelper.cpp
- xcb/dnotitlebarwindowhelper.h
Issue: https://github.com/linuxdeepin/developer-center/issues/6579
> fix: valid properties read faild(#6579)

- debian/changelog
> chore: bump version to 5.6.21

- xcb/dplatformintegration.cpp
Add lcDxcb, default log level is info.
Log: add category logging
> chore: add category logging

- xcb/dnotitlebarwindowhelper.cpp
拼写错误
Log: 修复阴影补偿属性无法设置的问题
Bug: https://pms.uniontech.com/bug-view-242761.html
Influence: 阴影补偿属性
> fix: 修复阴影补偿属性无法设置的问题

- xcb/CMakeLists.txt
Log: fix build failure on openSUSE Tumbleweed
> fix: Need link Qt6DBus library

- xcb/dnotitlebarwindowhelper.cpp
> fix: app crashed when window destroyed in quick
