- platformplugin/dplatformwindowhelper.cpp
On KWin
https://github.com/linuxdeepin/internal-discussion/issues/1430
https://github.com/linuxdeepin/internal-discussion/issues/1346
修复在kwin中，窗口第一次启动后输入框无法获取焦点（qcef应用稳定出现）
> fix: window can not get focus at mapped

- platformplugin/dforeignplatformwindow.h
- platformplugin/dforeignplatformwindow_x11.cpp
the "xcbScreen()" is nullptr
https://github.com/linuxdeepin/internal-discussion/issues/1471
> fix: crash at DForeignPlatformWindow::handleConfigureNotifyEvent

- platformplugin/dforeignplatformwindow_x11.cpp
修复DForeignPlatformWindow窗口根据窗口geometry计算其所在屏幕结果错误
> fix: the foreign platform window screen is wrong at initialize

- platformplugin/utility_x11.cpp
> fix: the window menu cannot hide

- platformplugin/dframewindow.cpp
在DFrameWindow窗口销毁时销毁QPlatformBackingStore对象
> fix: delete platform backing store object

- platformplugin/xcbnativeeventfilter.cpp
禁用对 XIQueryDevice 的调用，可能会导致进程卡在 XReply
如：greeter/dde-lock 放置一夜后进程卡死
> fix: do not call XIQueryDevice

- platformplugin/dxcbxsettings.cpp
```
dxcbxsettings.cpp:51:8: error: redefinition of ‘struct QStdFreeDeleter’
51 | struct QStdFreeDeleter {
|        ^~~~~~~~~~~~~~~
In file included from /usr/include/qtxcb-private/qxcbconnection.h:56,
from /usr/include/qtxcb-private/qxcbobject.h:43,
from /usr/include/qtxcb-private/qxcbscreen.h:51,
from dxcbxsettings.h:43,
from dxcbxsettings.cpp:40:
/usr/include/qtxcb-private/qxcbconnection_basic.h:160:8: note: previous definition of ‘struct QStdFreeDeleter’
160 | struct QStdFreeDeleter {
|        ^~~~~~~~~~~~~~~
make[1]: *** [Makefile.qt5platform-plugin:550: dxcbxsettings.o] Error 1
```
> fix: build failure under Qt 5.13

- platformplugin/dnativesettings.cpp
- platformplugin/dplatformintegration.h
- platformplugin/dxcbxsettings.cpp
- platformplugin/dxcbxsettings.h
- platformplugin/xcbnativeeventfilter.cpp
窗口的属性改变事件可能会被其它事件过滤器接收并处理
因此改用client message通知窗口级别的xsettings属性变化
此client message事件发送给xsettings owner，且在事件数据
中携带属性变化窗口的window id。
> fix: use client message notify window xsettings changed

- platformplugin/dnotitlebarwindowhelper.cpp
fix window background blur is invalid when kwin restart
修复kwin重启会导致窗口的模糊属性丢失
> fix: update window blur property when hasBlurWindow is true

- platformplugin/dplatformintegration.cpp
- platformplugin/utility_x11.cpp
fix isEnableNoTitlebar return false of a no titlebar enabled window
修复设置空的模糊区域时无法清理窗口的模糊背景
修复窗口开启无标题栏模式后isEnableNoTitlebar返回的值错误
> fix: clear window blur property if the blur areas/paths is empty

- platformplugin/dnativesettings.cpp
- platformplugin/dnativesettings.h
- platformplugin/dplatformintegration.cpp
- platformplugin/dxcbxsettings.cpp
Use QAbstractDynamicMetaObject
支持通过QObject::property/setProperty读写未在QObject中定义对应属性的native设置项
> feat: support dynamic create properties for DNativeSettings

- wayland/wayland-shell/dwaylandshellmanager.cpp
app can use qwindow->setproperty(_d_dwayland_staysontop, true/false)
to request keep Above or not
Log:
Influence: wayland keepabove
> chore: update window property when keepabovechanged

- wayland/wayland-shell/dwaylandshellmanager.cpp
wayland 环境下 dock 上的右键菜单位置偏移
Log:
Bug: https://pms.uniontech.com/bug-view-126033.html
Influence: 右键菜单的位置
> fix: wayland dock 右键菜单位置偏移

- wayland/wayland-shell/dwaylandshellmanager.cpp
如果菜单不是tootip的role,显示时会一闪就关闭,因为收到两次activeChanged,
一次为null一次为menu，导致菜单显示后立即被关闭
Log:
Influence: wayland环境的右键菜单
> chore: 非tooltip菜单无法显示的问题优化

- wayland/wayland-shell/dwaylandshellmanager.cpp
stateChange 时，Active的状态不能单独发给Qt
Log:
Bug: https://pms.uniontech.com/bug-view-124371.html
Influence:
> fix: 影院最小化还原后未恢复播放

- xcb/libqt5xcbqpa-dev/5.15.4/qxcbatom.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbbackingstore.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbclipboard.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbconnection.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbconnection_basic.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbcursor.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbdrag.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbeventdispatcher.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbeventqueue.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbexport.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbimage.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbintegration.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbkeyboard.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbmime.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbnativeinterface.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbobject.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbscreen.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbsessionmanager.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbsystemtraytracker.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbvulkaninstance.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbvulkanwindow.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbwindow.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbwmsupport.h
- xcb/libqt5xcbqpa-dev/5.15.4/qxcbxsettings.h
Qt 5.15.4 source code is now published, see:
- https://download.qt.io/archive/qt/5.15/5.15.4/
- https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb?h=v5.15.4-lts-lgpl
> Add Qt 5.15.4 headers

- wayland/wayland-shell/dwaylandshellmanager.cpp
QPointer 为 non-POD 类型的，会减缓库的加载速度
https://github.com/KDE/clazy/blob/1.10/docs/checks/README-non-pod-global-static.md
Log:
Influence:
> chore: fix no-POD static warnings

- wayland/wayland-shell/main.cpp
v23版本xdg-shell-v6废弃，创建失败则创建xdg-shell
Log:
Influence:
> chore: 支持v23版本创建xdg-shell

- src/global.h
- wayland/wayland-shell/dwaylandshellmanager.cpp
1. 增加windowInWorkArea属性
2. 创建PlasmaWindowManagement对象
3. 将属性windowInWorkSpace传给窗管处理
Log: 修复wayland下切换工作区，窗口隐藏问题
Bug: https://pms.uniontech.com/bug-view-109805.html
Influence: wayland 切换工作区窗口隐藏
> fix: wayland下切换工作区，窗口隐藏

- debian/control
debian/control:dde-qt5wayland-plugin 运行依赖加上 qtwayland5
Log: dde-qt5wayland-plugin 运行依赖加上 qtwayland5
Task: https://pms.uniontech.com/task-view-147965.html
Influence: dde-qt5wayland-plugin 运行依赖
> chore: dde-qt5wayland-plugin 运行依赖加上 qtwayland5

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
- wayland/wayland-shell/main.cpp
创建blur模块，通过clipPath属性传的region设置模糊区
Log: 修复锁屏界面网络面板显示异常，底色有重叠黑影问题
Bug: https://pms.uniontech.com/bug-view-124427.html
Influence: darrowRectangle
Change-Id: I27b19539c3f228e83d36246e8f39cbd9e76e88ed
> fix: 锁屏界面网络面板显示异常，底色有重叠黑影

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
1.绘制模糊区域时重新创建region。
2.模糊去使能和窗口綁定。
Log: 解決wayland控制中心时区背景模糊问题
Bug: https://pms.uniontech.com/bug-view-126387.html
Influence: 时区模糊背景
Change-Id: I12435abbb47c9aa2762ac783b15e701cdd347481
> fix: wayland控制中心时区背景模糊问题

- wayland/dwayland/dwaylandintegration.cpp
- wayland/dwayland/dwaylandintegration.h
dwayland通过xsettings获取主屏信息的变化，用于实现wayland下主屏设置功能
确保qt接口和display服务的主屏数据一致
Log: 解决wayland下主屏功能异常问题
Influence: 当主屏发生变化后，及时更新到xsettings
Bug: https://pms.uniontech.com/bug-view-146451.html
Change-Id: I25ad8568e16e2b40534a036688866af25910342d
> fix: 当主屏发生变化后，及时更新到xsettings

- wayland/dwayland/dhighdpi.cpp
- wayland/dwayland/dhighdpi.h
当屏幕被移除主动从 cache 中删除对应的缓存
使得下次再添加屏幕时，屏幕的的缩放从环境变量
或者xsettings中获取
Log:
Bug: https://pms.uniontech.com/bug-view-127439.html
Influence: wayland screen factor
Change-Id: Ib99a85e348e430741123c34c470eb1384b91697f
> fix: 屏幕移除后没有更新缓存的问题

- wayland/wayland-shell/main.cpp
修改对环境变量的判断为
对是否支持xdg-shell-v6接口的判断
Log: 修改对xdg-shell-v6的判断
Influence: wayland
Change-Id: I368f48fb1f5e3b7e81bdb38b5f498373be4455ae
> chore: 判断是否支持xdg-shell-v6

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- wayland/dwayland/dnotitlebarwindowhelper_wl.h
std::bind 的方式会打印很多警告日志。
Log:
Influence: logs
Change-Id: I958ccc76ba9b91496cdeef1ce65c51c9b54ea07b
> chore: 去掉使用std::bind的方式hook

- src/global.h
- xcb/dplatformintegration.cpp
- xcb/dplatformintegration.h
- xcb/dplatformnativeinterfacehook.cpp
Consider some singletons, or applications that start another program.
They generally don't show windows. There is no end to the start queue,
and the startid exposed by QPA in Qt indicates this type of application
processing. It is now handled uniformly in the platform plugin dxcb.
It is worth noting that this type of application needs to ensure that the
Application object is released when it exits.
Log: Fixed some singletons not ending the startup queue
> End the start queue when startid is not used

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- wayland/dwayland/dnotitlebarwindowhelper_wl.h
- wayland/dwayland/dwaylandinterfacehook.cpp
it is error when returned value of dde_shell_surface->isSplitable()
has changed, because we need to request a status from kwin instead of window's property, so we shouldn't compare old value and setted value.
Log: 是否分屏请求状态错误
Bug: https://pms.uniontech.com/bug-view-137573.html
Influence: 分屏菜单是否弹出
Change-Id: I3dfb9da4972fc7b851e4141e68cc9f646955d4ab
> fix: supportForSplittingWindow return error

- xcb/dplatformnativeinterfacehook.cpp
functionCache数据初始化supportForSplittingWindow
和sendEndStartupNotifition多了个逗号
Log: 
Change-Id: I8c991137a08a519e8b56a16a45ec6602bd1c73b0
> chore: functionCache数据初始化时多了个逗号

- wayland/dwayland/dwaylandintegration.cpp
qt屏幕添加信号可能晚于xsetting，当设置主屏时，屏幕还未添加，通过监听qt屏幕添加信号，避免主屏设置不对
Log: 修复设置任务栏跟随主屏，切换显示模式时，概率性出现任务栏不在主屏的问题
Influence: 主屏幕设置
Bug: https://pms.uniontech.com/bug-view-159837.html
> fix: 修复设置任务栏跟随主屏，切换显示模式时，概率性出现任务栏不在主屏的问题

- wayland/wayland-shell/dwaylandshellmanager.cpp
增加kwayland_surface和kwayland_manage的空指针判断
Log: 增加空指针判断
Influence: blur模块
Change-Id: I465a31f652a432c6767214c15d1f9891beef1cf8
> chore: 空指针判断

- xcb/windoweventhook.cpp
- xcb/windoweventhook.h
Qt 修复焦点问题后插件中 hook focusInEvent 的地方微调
Bug: https://pms.uniontech.com/bug-view-165587.html,https://pms.uniontech.com/bug-view-164477.html
Log: 桌面重命名焦点问题
Change-Id: Ic21d78844cb65743e185b716e9218e9dc152dbcf
> fix: 桌面文件重命名焦点丢失

- wayland/dwayland/dwaylandintegration.cpp
- xcb/dplatformintegration.cpp
Don't show shortcuts in context menu
QDeepinTheme::themeHint(ShowShortcutsInContextMenus) return false not work anymore see https://codereview.qt-project.org/c/qt/qtbase/+/351295
Bug: https://pms.uniontech.com/bug-view-167667.html
Log: Don't Show Shortcuts In Context Menus
Change-Id: Ib290a2a51e2bfd3e14e95c12d660812ef82bf36c
> fix: shotcuts show in context menu

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
- wayland/wayland-shell/main.cpp
在任务栏发送dock-appitem-geometry过来时，调用wayland协议的接口去设置应用的窗口最小化位置
Log: 修复wayland下最小化魔灯效果显示异常的问题
Bug: https://pms.uniontech.com/bug-view-111637.html
Influence: wayland下应用窗口最小化显示效果
Change-Id: Ic53215f2f18f8f2502c7ef16d9aafe7cbb7da326
> fix: wayland下最小化魔灯效果显示异常

- src/global.h
- wayland/dwayland/dwaylandinterfacehook.cpp
- wayland/dwayland/dwaylandinterfacehook.h
- wayland/wayland-shell/dwaylandshellmanager.cpp
- xcb/dplatformnativeinterfacehook.cpp
- xcb/utility.h
- xcb/utility_x11.cpp
Add function to be compatible with two split screen.
Log: x11和wayland下支持多分屏
Task: https://pms.uniontech.com/task-view-180357.html
Influence: 需要依赖窗管升级，才能实现多分屏效果
Change-Id: I4abd73b8418f280a97caa9d5a46b76454a5d105e
> feat: Support multi split screen

- archlinux/PKGBUILD
- xcb/linux.pri
Add QT_XCB_PRIVATE_INCLUDE option in qmake build config file. You can set it for the qmake command, if its value is not empty, will using it on build and ignore the libqt5xcbqpa-dev/* files in project.
> Allow specify include path of qtxcb private headers

- xcb/main.cpp
当桌面环境名称为 DDE 时，载入 dxcb 插件。
相关：
- https://github.com/linuxdeepin/dde-session/pull/7
- https://github.com/linuxdeepin/developer-center/issues/3829
> chore: load dxcb if XDG_CURRENT_DESKTOP set to DDE

- wayland/dwayland/dwaylandintegration.cpp
当设置主屏为VGA时,登录到桌面或者重启桌面,主屏会从HDMI变到VGA,是因为DWaylandIntegration初始化时只做了连接,并没有设置主屏,因此在连接前设置一次主屏
Log: 修复桌面启动时主屏闪变
Bug: https://pms.uniontech.com/bug-view-195723.html
Influence: 主屏设置 dwayland
> fix: 修复桌面启动时主屏闪变

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
use QTWAYLANDCLIENT_VERSION instead of QT_VERSION
qt 版本和 qtwayland 版本不是一致的.
> chore: QTWAYLANDCLIENT_VERSION check

- xcb/windoweventhook.cpp
Drag a file into the window and drop, the mouse state should be from Leftbutton to NoButton. 
But the current mouse state is always Leftbutton, which causes the window to be resized when moving the mouse beside the edge.
Update the mouse buttons' state by querying the state from xserver.
Issue: https://github.com/linuxdeepin/dtk/issues/63
> fix: deepin-movie's window is resized when moving the mouse beside the edge

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
onWlSurfaceCreated emit before createShellSurface
> fix: qt app server decoration not created

- wayland/wayland-shell/dwaylandshellmanager.cpp
- wayland/wayland-shell/dwaylandshellmanager.h
createShellSurface 函数执行中 QWaylandWIndow::shellSurface 还未赋值，此时访问是空值。
window->shellSurface(); // nullptr
shellSurface->window(); //  ok
把 ensureDDEShell 参数改成 shellSurface
> fix: ensue ddeshell failed

- CMakeLists.txt
set the default install prefix to /usr
Log: set the default install prefix of cmake
> chore: set the default install prefix of cmake

- xcb/dplatformwindowhelper.cpp
due to using the wrong cast (dynamic_cast), the pointer is nullptr.
Log: solve the issue that the application crashed when moving the window
> fix: application crashed when moving the window

- xcb/dnotitlebarwindowhelper.cpp
qstring type can't be convert to qstringlist type
Log: fix the issue that call setWindowRadius failed
> fix: call setWindowRadius failed

- xcb/dplatformwindowhelper.cpp
add qt version macro to control the file
Log: can't find qeventpoint_p.h in qt5
> fix: can't find qeventpoint_p.h in qt5

- xcb/dplatformwindowhelper.cpp
typed wrong window type when adapting to Qt6
Log: fix the autoStarted app crashed when dragging it
> fix: the autoStarted app crashed when dragging it

- wayland/wayland-shell/wayland-shell.cmake
DWayland uses ECM's module to find Wayland and everything using it will fail to find Wayland without ECM.
Fixes building on Arch.
> fix: use ECM to help DWayland find Wayland

- xcb/dplatformintegration.cpp
xcb插件设置了wayland下运行xcb应用不支持dxcb
Log: 
Influence: 所有在wayland下运行的x窗口
> fix: 修复远程协助关于对话框透明

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- xcb/dnotitlebarwindowhelper.cpp
from https://github.com/linuxdeepin/dtkwidget/pull/200 通过窗口管理器移动窗口时，鼠标按下并移动，之后事件由窗管接管
移动结束后，应用无法收到鼠标释放的事件，导致没有刷新全局的 qt_button_down
此时 sendMouseEvent 无法走到 dispatchEnterLeave 即没有 enter/leave 事件触发，也就没有了 hover 状态。收到 mouse move 且没有鼠标按下的状态时 置空 qt_button_down
Log: 修复当窗口标题栏跟dock栏有重叠时，分屏菜单不显示
Bug: https://pms.uniontech.com/bug-view-157629.html
Influence: 所有使用DTK标题栏的窗口
> fix: 修复当窗口标题栏跟dock栏有重叠时，分屏菜单不显示

- CMakeLists.txt
- wayland/dwayland/CMakeLists.txt
- wayland/wayland-shell/CMakeLists.txt
Moving compile generated plugins from source directory to
build directory.
> refact: move compile generated plugins to build directory

- src/dnativesettings.cpp
buildNativeSettings 之后 metaobject 被替换了
不会走原来的 read 方法了。
这里如果读取时 xsettings 中如果没有 fallback 到
base 对象的 read 方法
Issue: https://github.com/linuxdeepin/dtk/issues/101
> fix: DPlatformTheme::property not work

- xcb/dnotitlebarwindowhelper.cpp
- xcb/dnotitlebarwindowhelper.h
commit 1272c423 引入base 的 property/setProperty 会走自己的 read/write 方法，这里直接在 read/write 方法中调用 property/setProperty 会导致递归调用最终栈溢出崩溃
解决办法： 加一个 nativesettings 代理，并且通过同名 property/setProperty 函数隐藏父类的实现
> fix: stack overflow with property/setProperty

- debian/changelog
- xcb/dxcbwmsupport.cpp
hasComposite is not a requirement for hasBlurWindow
Issue: https://github.com/linuxdeepin/developer-center/issues/7057
> fix: blurWindow not update (bump to 5.6.22)

- src/vtablehook.h
If the object does not implement `QDebug operator<<(QDebug , const Object *)` it cannot be printed with QDebug
> chore: avoid build error 

- xcb/dnotitlebarwindowhelper.cpp
incorrect count is assigned in
*(reinterpret_cast<const QVector<qint32>*>(&area), it causes invalid
BlurArea, and causes memory leakage.
It causes in the commit https://github.com/linuxdeepin/dtkgui/pull/232
> fix: BlurArea unpack error in qt5

- src/dnativesettings.cpp
QByteArray类型没减去偏移量,在最后对整体QMetaObjectBuilder减偏移量时导致普通类型都被多减了一次 (从QMetaProperty到QMetaPropertyBuilder使用addProperty会自动处理偏移量) 两种方案:
1. 如果在最后统一处理,索引应该使用mp.notifySignalIndex()而不是op.notifySignal().index()
2. 在处理QByteArray类型时减去偏移量
Log: 修复边界颜色,边框宽度,阴影颜色,偏移量等窗口属性等不能实时变化
Issue: https://github.com/linuxdeepin/developer-center/issues/8342
Influence: 边界颜色,边框宽度,阴影颜色,偏移量等窗口属性
> fix: window border properties cannot change in real time

- xcb/dnotitlebarwindowhelper.cpp
- xcb/dnotitlebarwindowhelper.h
- fix: 向日葵中点击文管窗口标题时直接进入移动窗口状态
- fix: 共享库二进制兼容
- fix: incorect window movement when selecting files
> fix: incorect window movement when selecting files

- src/vtablehook.cpp
- xcb/dnotitlebarwindowhelper.cpp
- fix: hasVtable is incorrect when destructing
- fix: app crashed when window destroyed in quick
> fix: app crashed when window destroyed in quick

- xcb/dnotitlebarwindowhelper.cpp
DNotitebarWindowHelper is delete by manual instead of Window
deleted, so we need to resetVtable.
pms: BUG-368399
> fix: app crashed for DNotitebarWindowHelper

- xcb/dhighdpi.cpp
Using a variable to avoid reallocating memory.
pms: BUG-292371
> fix: app crashed when QBytearray reallocated

- xcb/dplatformintegration.cpp
Monitor the Gtk/CursorThemeName property and manually call changeCursor() to refresh the cursor when it changes
pms: BUG-296269
> fix: after setting the cursor theme, it will not update in real-time.

- wayland/dwayland/dnotitlebarwindowhelper_wl.cpp
- xcb/dnotitlebarwindowhelper.cpp
qobject_cast<QWindow*>(window) is returned nullptr if window is destroyed in qt6, and we can see it on tst_QWindow::qobject_castOnDestruction() in tst_qwindow.cpp.
pms: BUG-299239
> fix: DNotitlebarWindowHelper can't be removed from mapped

- xcb/dnotitlebarwindowhelper.cpp
- xcb/dnotitlebarwindowhelper.h
- xcb/dplatformintegration.cpp
Window is recreated if Window's flags is Qt::ToolTip and missing
WindowStaysOnTopHint, in case, Qt will append WindowStaysOnTopHint
flag to the window in QXcbWindow::setWindowFlags, it causes
window is recreated in qt6.
We reconstruct DNoTitlebarWindowHelper to update xsettings value.
We can also add WindowStaysOnTopHint for the window.
pms: BUG-302661
> fix: ToolTip's xsettings can't work in qt6

- xcb/dframewindow.cpp
- xcb/dplatformwindowhelper.cpp
Timer maybe miss killed.
MouseEvent conversion is wrong in qt6, old way will be called
recursively.
requestActivateWindow is called recurisvely in qt6.
pms: TASK-368399
> fix: adapt to qt6 for PlatformWindowHelper

- xcb/dnotitlebarwindowhelper.cpp
- xcb/dnotitlebarwindowhelper.h
- xcb/utility.h
- xcb/utility_x11.cpp
1. Added touch drag support for QQuickWindow with proper grabber state
tracking
2. Implemented multi-screen aware touch drag handling with position
validation
3. Added new Utility::updateMousePointForWindowMove overload for custom
positions
4. Improved window boundary checks using scene coordinates
5. Added debug logging for window drag operations
The changes enable proper touch-based window dragging for QML-based
applications while maintaining existing mouse drag functionality. The
implementation tracks touch grabber states to determine if QML items
have handled the touch events, and only initiates window dragging when
no QML items have claimed the touch points. The multi-screen support
ensures correct behavior across different display configurations.
feat: 增强QML窗口的触摸拖拽支持
1. …
> feat: enhance touch drag support for QML windows in qt6

- .github/workflows/call-auto-release.yml
- rpm/qt5platform-plugins.spec
1. Changed version input from required to optional in GitHub workflow to
allow more flexible release process
2. Updated rpm spec file formatting for consistency
3. Added %{?dist} macro to Release field for better compatibility with
different distributions
fix: 使版本号在发布工作流中可选并更新 rpm 规范
1. 将 GitHub 工作流中的版本输入从必选改为可选，以实现更灵活的发布流程
2. 更新 rpm 规范文件格式以提高一致性
3. 在 Release 字段中添加 %{?dist} 宏以提高与不同发行版的兼容性
> fix: make version optional in release workflow and update rpm spec

- debian/rules
1. Added security hardening compiler flags to debian/rules
2. Enabled stack protection with -fstack-protector-all
3. Added RELRO, NOW, and noexecstack linker flags
4. Included additional warning flags (-Wall) for stricter compilation
5. These changes improve binary security against common exploits
feat: 添加安全加固编译参数
1. 在 debian/rules 中添加安全加固编译参数
2. 使用 -fstack-protector-all 启用栈保护
3. 添加 RELRO、NOW 和 noexecstack 链接器标志
4. 包含额外的警告标志 (-Wall) 用于更严格的编译
5. 这些更改提高了二进制文件对常见漏洞的防护能力
> feat: add security hardening build flags

- src/ddesktopinputselectioncontrol.cpp
- src/dnativesettings.h
- src/dplatformsettings.h
- src/dselectedtexttooltip.cpp
- src/dselectedtexttooltip.h
- src/dxcbxsettings.cpp
- src/dxcbxsettings.h
- xcb/dframewindow.cpp
- xcb/dhighdpi.cpp
- xcb/dnotitlebarwindowhelper.cpp
- xcb/dplatformwindowhelper.cpp
1. Added Qt6 version checks for touch/mouse event handling with new API
(globalPosition vs screenPos)
2. Marked DNativeSettings, DPlatformSettings and DXcbXSettings classes
as Q_DECL_HIDDEN
3. Replaced QGuiApplication::fontChanged signal with event filter for
Qt6 compatibility
4. Updated type checking from QVariant::type() to typeId() for Qt6
5. Fixed window geometry calculations for Qt6 mouse position handling
6. Adjusted DHighDpi initialization logic for Qt6 where high DPI is
always enabled
7. Added proper private section to DPlatformSettings class
fix: 添加Qt6兼容性并解决编译警告
1. 为触摸/鼠标事件处理添加Qt6版本检查，使用新API（globalPosition替
代screenPos）
2. 将DNativeSettings、DPlatformSettings和DXcbXSettings类标记为
Q_DECL_HIDDEN
3. 为Qt6兼容性使用事件过滤器替代QGuiApplication::fontChanged信号
4. 将类型检查从QVariant::type()更新为typeId()以兼容Qt6 …
> fix: add Qt6 compatibility and resolve build warnings
